# Generated by Django 3.2.25 on 2024-10-26 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('region', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('topic', models.CharField(choices=[('Engrais solides', 'Engrais solides'), ('Engrais spéciaux hydrosolubles', 'Engrais spéciaux hydrosolubles'), ('Correcteurs de carence', 'Correcteurs de carence'), ('Biostimulants', 'Biostimulants')], max_length=50)),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
